title: The Perry Group
email: your-email@example.com
url: "http://theperry.group"
permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["strikethrough", "no_intra_emphasis", "with_toc_data", "lax_spacing", "highlight", "hard_wrap", "underline", "prettify"]
sass:
    sass_dir: _sass

plugins:
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-menus
#  - jekyll-minimagick

# Social
twitter: theperrygrouput

# Verification
verifyGoogle: kj4LGd8cy7r65lHFUlZ3e3GwenLepI_GyTyWCrNMC0Q
verifyPinterest: bab86c858262d986316ac81a31ad1326
verifyNorton: q60-ihfhkn48u6nuervqiazb9tdombuzwqbs25oo8dm6le4orlgigd1hxmo9fzjtupcp170nroz6g02c5p77lorkxg28o0bbjngzne0npr4s0cfp8yzodak5dguqlcj3
verifyYandex: 293210a66ec684d3

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
     layout: "posts"
     shortname: museseo
     permalink: /blog/:title/
#     menus: header
