title: The Perry Group
# email: your-email@example.com
description: The Perry Group is an awesome real estate group that specializes in the Salt Lake/Sugarhouse area of Utah.
url: "http://theperry.group"
permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata]
timezone: America/Denver

# Build settings
sass:
    sass_dir: _sass

plugins:
  - jekyll/tagging
  - jekyll-tagging-related_posts

# Social
twitter_site: theperrygrouput
twitter_creator: michaelperry123

# Verification
verifyGoogle: l-K_A3ptM0JETLZmEIagcfugyn1agJZMWQrICgRDDPs
verifyPinterest: 2c854258dd50ad351f7e57e9c92521b6
#verifyNorton: q60-ihfhkn48u6nuervqiazb9tdombuzwqbs25oo8dm6le4orlgigd1hxmo9fzjtupcp170nroz6g02c5p77lorkxg28o0bbjngzne0npr4s0cfp8yzodak5dguqlcj3
#verifyYandex: 293210a66ec684d3

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
     layout: "post"
     permalink: /blog/:title/
