---
upload_path: "/assets/banners"
frontmatter_file_url_template: "/assets/:year:/:month:/:day:"
body_file_url_template: "/assets/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
