---
upload_path: "/assets/banners"
frontmatter_file_url_template: "/assets/banners"
body_file_url_template: "/assets/banners"
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
collections:
